<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>KapeIR.Triage</AssemblyName>
    <RootNamespace>KapeIR.Triage</RootNamespace>
    <Product>KapeIR.Triage</Product>
    <AssemblyTitle>KapeIR.Triage</AssemblyTitle>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.IO" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\KapeIR.Core\KapeIR.Core.csproj" />
    <ProjectReference Include="..\KapeIR.Ui\KapeIR.Ui.csproj" />
    <Resource Include="app.ico" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="KapeIR.Builder.Tests" />
  </ItemGroup>
</Project>
